### ISSUE TITLE
error: 'transform_reduce' is not a member of 'std'

### ISSUE THREAD

**Issue by vbraun** [JohnCremona/eclib#88]
When trying to build with gcc (GCC) 14.3.1 20250523:
```
[eclib-20250616] [spkg-install] marith.cc: In function 'bigint factorback(const std::vector<NTL::ZZ>&, const std::vector<int>&)':
[eclib-20250616] [spkg-install] marith.cc:1302:15: error: 'transform_reduce' is not a member of 'std'
[eclib-20250616] [spkg-install]  1302 |   return std::transform_reduce(PP.cbegin(), PP.cend(), EE.cbegin(),
[eclib-20250616] [spkg-install]       |               ^~~~~~~~~~~~~~~~
[eclib-20250616] [spkg-install] make[3]: *** [Makefile:624: marith.lo] Error 1
```
Possibly a bit too bleeding-edge...

**Comment by JohnCremona** [comment]
I know what this is.  Transform_reduce needs the 2017 version of STL.  In eclib's configure.ac in line 59 it only requires version 2014.  Can you see if changing '14' to '17' on that line helps?  If not, I'll have to rewrite the one function which uses transform_reduce.
